/**
 * Der Erbe-Fragebaum (ERBE_DESIGN.md §2).
 *
 * 141 Knoten, 80 Ergebnisse, Tiefe 9. Die Struktur ist wörtlich uebernommen:
 * Wiederholte Teilbaeume bleiben wiederholt, und derselbe Ergebnistext steht
 * mehrfach in dieser Datei. Ein Knotengraph mit geteilten Ids wäre kürzer und
 * wäre die falsche Wahl (ADR-0002): Die Juristinnen pflegen einen Baum, und
 * zwei Pfade, die heute denselben Text zeigen, dürfen ihn morgen
 * unterschiedlich zeigen.
 *
 * Einmalig aus dem Werkzeugexport übertragen, danach von Hand gepflegt. Einen
 * Importschritt wie beim Rechtskatalog (DESIGN.md §8) gibt es hier nicht: Der
 * Export benutzt `/n` und `n/` gemischt als Umbruch, trägt Regieanweisungen im
 * Fließtext ("(Eingabefeld zum Suchen)") und englische Antwortlabels an
 * deutschen Fragen. Ein Parser, der das dauerhaft auflöste, wäre
 * zerbrechlicher als die Daten, die er erzeugt.
 *
 * Die Ids sind undurchsichtig und stehen in der Adresse. Sie bleiben stabil:
 * Ein umnummerierter Knoten macht aus einem geteilten Link eine andere Frage.
 */

import type { Fragebaumknoten } from '../types/fragebaum.ts'

/** Der Einstieg: "Sind Sie Erbe?" */
export const WURZEL = 'n0'

export const FRAGEBAUM: Fragebaumknoten[] = [
  {
    id: 'n0',
    art: 'frage',
    text: 'Sind Sie Erbe?',
    antworten: [
      { text: 'Ja', ziel: 'n1' },
      { text: 'Nein', ziel: 'n50' },
      { text: 'Ich weiß es nicht', ziel: 'n57' },
    ],
  },
  {
    id: 'n1',
    art: 'frage',
    text: 'Haben Sie ein Testament gefunden?',
    antworten: [
      { text: 'Ja', ziel: 'n2' },
      { text: 'Nein', ziel: 'n18' },
      { text: 'Ich bin mir unsicher, ob das ein Testament ist', ziel: 'n33' },
    ],
  },
  {
    id: 'n2',
    art: 'frage',
    text: 'Was mache ich, wenn ich ein Testament gefunden habe?\n• Testament unverzüglich beim zuständigen Nachlassgericht abgeben\n• Hinweis: Eine Nicht-Abgabe kann zu strafrechtlichen Folgen und Kosten für Sie führen.\n• Die Frist zur Abgabe ist unverzüglich (ohne schuldhaftes Zögern).',
    aufgabe: 'testament',
    gericht: true,
    antworten: [
      { text: 'Weiter zu Fragen über das Erbe', ziel: 'n3' },
    ],
  },
  {
    id: 'n3',
    art: 'frage',
    text: 'Hat sich das Nachlassgericht bei Ihnen gemeldet?',
    antworten: [
      { text: 'Ja', ziel: 'n4' },
      { text: 'Nein', ziel: 'n8' },
    ],
  },
  {
    id: 'n4',
    art: 'frage',
    text: 'Wollen Sie das Erbe haben?',
    hinweis: 'Zum Erbe können auch Schulden des Verstorbenen gehören. Daher können auf den Erben Kosten zukommen. Außerdem kann es bei angespannten Situationen zwischen Erben zu Streitigkeiten kommen, die vor Gericht enden können. Wenn man das Erbe nicht will, dann erhält man nichts - also auch keinen Pflichtteil.',
    info: 'pflichtteil',
    antworten: [
      { text: 'Ja, ich will das Erbe', ziel: 'n6' },
      { text: 'Nein, ich will das Erbe nicht', ziel: 'n7' },
    ],
  },
  {
    id: 'n6',
    art: 'ergebnis',
    text: 'Sie sind Erbe.',
    status: 'erbe',
    antworten: [],
  },
  {
    id: 'n7',
    art: 'ergebnis',
    text: 'Sie wollen das Erbe nicht (Ausschlagung)\n**Folgende Schritte sind jetzt für Sie relevant:**\n\n**1. Frist**\nDie Frist beträgt 6 Wochen.\nFristbeginn:\n[gruen:Normalfall (gesetzliche Erbfolge):] Die Frist läuft ab dem Moment, in dem Sie erfahren, dass die Person gestorben ist und Sie gesetzlich erben.\n[gruen:Testament oder Erbvertrag:] Gibt es ein Testament, läuft die Frist erst los, wenn das Nachlassgericht Ihnen dieses Testament offiziell eröffnet und mitgeteilt hat – selbst wenn Sie vorher schon von dem Dokument wissen.\n\n**2. Wie können Sie das Erbe ablehnen?**\nSie haben dafür zwei Möglichkeiten:\n[gruen:1. Über ein Notariat:]\n• Termin bei einem Notar vereinbaren\n• Antrag auf Ausschlagung stellen\n• Notar beurkundet den Antrag und schickt ihn an das Nachlassgericht\n\n[gruen:2. Persönlich beim Gericht:]\n• telefonisch Termin beim Nachlassgericht vereinbaren\n• persönlich beim Nachlassgericht erscheinen\n\n**Notar oder Nachlassgericht:**\n• Beim Notar erhalten Sie schneller und sicher innerhalb der Frist einen Termin\n• Beim Nachlassgericht fallen Ihnen keine zusätzlichen Kosten an',
    aufgabe: 'ausschlagung',
    status: 'noch-erbe',
    gericht: true,
    kenntnisdatum: true,
    ausschlagungshinweis: true,
    antworten: [],
  },
  {
    id: 'n8',
    art: 'frage',
    text: 'Gibt es ein Testament?',
    antworten: [
      { text: 'Ja', ziel: 'n9' },
      { text: 'Nein', ziel: 'n14' },
    ],
  },
  {
    id: 'n9',
    art: 'frage',
    text: 'Sie müssen warten bis sich das Nachlassgericht meldet.',
    antworten: [
      { text: 'Das Nachlassgericht hat sich gemeldet', ziel: 'n10' },
    ],
  },
  {
    id: 'n10',
    art: 'frage',
    text: 'Wollen Sie das Erbe haben?',
    hinweis: 'Zum Erbe können auch Schulden des Verstorbenen gehören. Daher können auf den Erben Kosten zukommen. Außerdem kann es bei angespannten Situationen zwischen Erben zu Streitigkeiten kommen, die vor Gericht enden können. Wenn man das Erbe nicht will, dann erhält man nichts - also auch keinen Pflichtteil.',
    info: 'pflichtteil',
    antworten: [
      { text: 'Ja, ich will das Erbe', ziel: 'n12' },
      { text: 'Nein, ich will das Erbe nicht', ziel: 'n13' },
    ],
  },
  {
    id: 'n12',
    art: 'ergebnis',
    text: 'Sie sind Erbe.',
    status: 'erbe',
    antworten: [],
  },
  {
    id: 'n13',
    art: 'ergebnis',
    text: 'Sie wollen das Erbe nicht (Ausschlagung)\n**Folgende Schritte sind jetzt für Sie relevant:**\n\n**1. Frist**\nDie Frist beträgt 6 Wochen.\nFristbeginn:\n[gruen:Normalfall (gesetzliche Erbfolge):] Die Frist läuft ab dem Moment, in dem Sie erfahren, dass die Person gestorben ist und Sie gesetzlich erben.\n[gruen:Testament oder Erbvertrag:] Gibt es ein Testament, läuft die Frist erst los, wenn das Nachlassgericht Ihnen dieses Testament offiziell eröffnet und mitgeteilt hat – selbst wenn Sie vorher schon von dem Dokument wissen.\n\n**2. Wie können Sie das Erbe ablehnen?**\nSie haben dafür zwei Möglichkeiten:\n[gruen:1. Über ein Notariat:]\n• Termin bei einem Notar vereinbaren\n• Antrag auf Ausschlagung stellen\n• Notar beurkundet den Antrag und schickt ihn an das Nachlassgericht\n\n[gruen:2. Persönlich beim Gericht:]\n• telefonisch Termin beim Nachlassgericht vereinbaren\n• persönlich beim Nachlassgericht erscheinen\n\n**Notar oder Nachlassgericht:**\n• Beim Notar erhalten Sie schneller und sicher innerhalb der Frist einen Termin\n• Beim Nachlassgericht fallen Ihnen keine zusätzlichen Kosten an',
    aufgabe: 'ausschlagung',
    status: 'noch-erbe',
    gericht: true,
    kenntnisdatum: true,
    ausschlagungshinweis: true,
    antworten: [],
  },
  {
    id: 'n14',
    art: 'frage',
    text: 'Wollen Sie das Erbe haben?',
    hinweis: 'Zum Erbe können auch Schulden des Verstorbenen gehören. Daher können auf den Erben Kosten zukommen. Außerdem kann es bei angespannten Situationen zwischen Erben zu Streitigkeiten kommen, die vor Gericht enden können. Wenn man das Erbe nicht will, dann erhält man nichts - also auch keinen Pflichtteil.',
    info: 'pflichtteil',
    antworten: [
      { text: 'Ja, ich will das Erbe', ziel: 'n16' },
      { text: 'Nein, ich will das Erbe nicht', ziel: 'n17' },
    ],
  },
  {
    id: 'n16',
    art: 'ergebnis',
    text: 'Sie sind Erbe.',
    status: 'erbe',
    antworten: [],
  },
  {
    id: 'n17',
    art: 'ergebnis',
    text: 'Sie wollen das Erbe nicht (Ausschlagung)\n**Folgende Schritte sind jetzt für Sie relevant:**\n\n**1. Frist**\nDie Frist beträgt 6 Wochen.\nFristbeginn:\n[gruen:Normalfall (gesetzliche Erbfolge):] Die Frist läuft ab dem Moment, in dem Sie erfahren, dass die Person gestorben ist und Sie gesetzlich erben.\n[gruen:Testament oder Erbvertrag:] Gibt es ein Testament, läuft die Frist erst los, wenn das Nachlassgericht Ihnen dieses Testament offiziell eröffnet und mitgeteilt hat – selbst wenn Sie vorher schon von dem Dokument wissen.\n\n**2. Wie können Sie das Erbe ablehnen?**\nSie haben dafür zwei Möglichkeiten:\n[gruen:1. Über ein Notariat:]\n• Termin bei einem Notar vereinbaren\n• Antrag auf Ausschlagung stellen\n• Notar beurkundet den Antrag und schickt ihn an das Nachlassgericht\n\n[gruen:2. Persönlich beim Gericht:]\n• telefonisch Termin beim Nachlassgericht vereinbaren\n• persönlich beim Nachlassgericht erscheinen\n\n**Notar oder Nachlassgericht:**\n• Beim Notar erhalten Sie schneller und sicher innerhalb der Frist einen Termin\n• Beim Nachlassgericht fallen Ihnen keine zusätzlichen Kosten an',
    aufgabe: 'ausschlagung',
    status: 'noch-erbe',
    gericht: true,
    kenntnisdatum: true,
    ausschlagungshinweis: true,
    antworten: [],
  },
  {
    id: 'n18',
    art: 'frage',
    text: 'Hat sich das Nachlassgericht bei Ihnen gemeldet?',
    antworten: [
      { text: 'Ja', ziel: 'n19' },
      { text: 'Nein', ziel: 'n23' },
    ],
  },
  {
    id: 'n19',
    art: 'frage',
    text: 'Wollen Sie das Erbe haben?',
    hinweis: 'Zum Erbe können auch Schulden des Verstorbenen gehören. Daher können auf den Erben Kosten zukommen. Außerdem kann es bei angespannten Situationen zwischen Erben zu Streitigkeiten kommen, die vor Gericht enden können. Wenn man das Erbe nicht will, dann erhält man nichts - also auch keinen Pflichtteil.',
    info: 'pflichtteil',
    antworten: [
      { text: 'Ja, ich will das Erbe', ziel: 'n21' },
      { text: 'Nein, ich will das Erbe nicht', ziel: 'n22' },
    ],
  },
  {
    id: 'n21',
    art: 'ergebnis',
    text: 'Sie sind Erbe.',
    status: 'erbe',
    antworten: [],
  },
  {
    id: 'n22',
    art: 'ergebnis',
    text: 'Sie wollen das Erbe nicht (Ausschlagung)\n**Folgende Schritte sind jetzt für Sie relevant:**\n\n**1. Frist**\nDie Frist beträgt 6 Wochen.\nFristbeginn:\n[gruen:Normalfall (gesetzliche Erbfolge):] Die Frist läuft ab dem Moment, in dem Sie erfahren, dass die Person gestorben ist und Sie gesetzlich erben.\n[gruen:Testament oder Erbvertrag:] Gibt es ein Testament, läuft die Frist erst los, wenn das Nachlassgericht Ihnen dieses Testament offiziell eröffnet und mitgeteilt hat – selbst wenn Sie vorher schon von dem Dokument wissen.\n\n**2. Wie können Sie das Erbe ablehnen?**\nSie haben dafür zwei Möglichkeiten:\n[gruen:1. Über ein Notariat:]\n• Termin bei einem Notar vereinbaren\n• Antrag auf Ausschlagung stellen\n• Notar beurkundet den Antrag und schickt ihn an das Nachlassgericht\n\n[gruen:2. Persönlich beim Gericht:]\n• telefonisch Termin beim Nachlassgericht vereinbaren\n• persönlich beim Nachlassgericht erscheinen\n\n**Notar oder Nachlassgericht:**\n• Beim Notar erhalten Sie schneller und sicher innerhalb der Frist einen Termin\n• Beim Nachlassgericht fallen Ihnen keine zusätzlichen Kosten an',
    aufgabe: 'ausschlagung',
    status: 'noch-erbe',
    gericht: true,
    kenntnisdatum: true,
    ausschlagungshinweis: true,
    antworten: [],
  },
  {
    id: 'n23',
    art: 'frage',
    text: 'Gibt es ein Testament?',
    antworten: [
      { text: 'Ja', ziel: 'n24' },
      { text: 'Nein', ziel: 'n29' },
    ],
  },
  {
    id: 'n24',
    art: 'frage',
    text: 'Sie müssen warten bis sich das Nachlassgericht meldet.',
    antworten: [
      { text: 'Das Nachlassgericht hat sich gemeldet', ziel: 'n25' },
    ],
  },
  {
    id: 'n25',
    art: 'frage',
    text: 'Wollen Sie das Erbe haben?',
    hinweis: 'Zum Erbe können auch Schulden des Verstorbenen gehören. Daher können auf den Erben Kosten zukommen. Außerdem kann es bei angespannten Situationen zwischen Erben zu Streitigkeiten kommen, die vor Gericht enden können. Wenn man das Erbe nicht will, dann erhält man nichts - also auch keinen Pflichtteil.',
    info: 'pflichtteil',
    antworten: [
      { text: 'Ja, ich will das Erbe', ziel: 'n27' },
      { text: 'Nein, ich will das Erbe nicht', ziel: 'n28' },
    ],
  },
  {
    id: 'n27',
    art: 'ergebnis',
    text: 'Sie sind Erbe.',
    status: 'erbe',
    antworten: [],
  },
  {
    id: 'n28',
    art: 'ergebnis',
    text: 'Sie wollen das Erbe nicht (Ausschlagung)\n**Folgende Schritte sind jetzt für Sie relevant:**\n\n**1. Frist**\nDie Frist beträgt 6 Wochen.\nFristbeginn:\n[gruen:Normalfall (gesetzliche Erbfolge):] Die Frist läuft ab dem Moment, in dem Sie erfahren, dass die Person gestorben ist und Sie gesetzlich erben.\n[gruen:Testament oder Erbvertrag:] Gibt es ein Testament, läuft die Frist erst los, wenn das Nachlassgericht Ihnen dieses Testament offiziell eröffnet und mitgeteilt hat – selbst wenn Sie vorher schon von dem Dokument wissen.\n\n**2. Wie können Sie das Erbe ablehnen?**\nSie haben dafür zwei Möglichkeiten:\n[gruen:1. Über ein Notariat:]\n• Termin bei einem Notar vereinbaren\n• Antrag auf Ausschlagung stellen\n• Notar beurkundet den Antrag und schickt ihn an das Nachlassgericht\n\n[gruen:2. Persönlich beim Gericht:]\n• telefonisch Termin beim Nachlassgericht vereinbaren\n• persönlich beim Nachlassgericht erscheinen\n\n**Notar oder Nachlassgericht:**\n• Beim Notar erhalten Sie schneller und sicher innerhalb der Frist einen Termin\n• Beim Nachlassgericht fallen Ihnen keine zusätzlichen Kosten an',
    aufgabe: 'ausschlagung',
    status: 'noch-erbe',
    gericht: true,
    kenntnisdatum: true,
    ausschlagungshinweis: true,
    antworten: [],
  },
  {
    id: 'n29',
    art: 'frage',
    text: 'Wollen Sie das Erbe haben?',
    hinweis: 'Zum Erbe können auch Schulden des Verstorbenen gehören. Daher können auf den Erben Kosten zukommen. Außerdem kann es bei angespannten Situationen zwischen Erben zu Streitigkeiten kommen, die vor Gericht enden können. Wenn man das Erbe nicht will, dann erhält man nichts - also auch keinen Pflichtteil.',
    info: 'pflichtteil',
    antworten: [
      { text: 'Ja, ich will das Erbe', ziel: 'n31' },
      { text: 'Nein, ich will das Erbe nicht', ziel: 'n32' },
    ],
  },
  {
    id: 'n31',
    art: 'ergebnis',
    text: 'Sie sind Erbe.',
    status: 'erbe',
    antworten: [],
  },
  {
    id: 'n32',
    art: 'ergebnis',
    text: 'Sie wollen das Erbe nicht (Ausschlagung)\n**Folgende Schritte sind jetzt für Sie relevant:**\n\n**1. Frist**\nDie Frist beträgt 6 Wochen.\nFristbeginn:\n[gruen:Normalfall (gesetzliche Erbfolge):] Die Frist läuft ab dem Moment, in dem Sie erfahren, dass die Person gestorben ist und Sie gesetzlich erben.\n[gruen:Testament oder Erbvertrag:] Gibt es ein Testament, läuft die Frist erst los, wenn das Nachlassgericht Ihnen dieses Testament offiziell eröffnet und mitgeteilt hat – selbst wenn Sie vorher schon von dem Dokument wissen.\n\n**2. Wie können Sie das Erbe ablehnen?**\nSie haben dafür zwei Möglichkeiten:\n[gruen:1. Über ein Notariat:]\n• Termin bei einem Notar vereinbaren\n• Antrag auf Ausschlagung stellen\n• Notar beurkundet den Antrag und schickt ihn an das Nachlassgericht\n\n[gruen:2. Persönlich beim Gericht:]\n• telefonisch Termin beim Nachlassgericht vereinbaren\n• persönlich beim Nachlassgericht erscheinen\n\n**Notar oder Nachlassgericht:**\n• Beim Notar erhalten Sie schneller und sicher innerhalb der Frist einen Termin\n• Beim Nachlassgericht fallen Ihnen keine zusätzlichen Kosten an',
    aufgabe: 'ausschlagung',
    status: 'noch-erbe',
    gericht: true,
    kenntnisdatum: true,
    ausschlagungshinweis: true,
    antworten: [],
  },
  {
    id: 'n33',
    art: 'frage',
    text: 'Wie erkenne ich ein Testament?\n**Aussehen**\n• handschriftlich von der verstorbenen Person geschrieben\n• die Unterschrift der verstorbenen Person steht unter dem Text\n• das Wort „Testament“ ist nicht notwendig\n• ein Testament kann auf einem beliebigen Material geschrieben sein\n**Inhalt**\nDas Testament macht in irgendeiner Form deutlich, wie das Vermögen aufgeteilt wird.',
    antworten: [
      { text: 'Weiter zu Fragen über das Erbe', ziel: 'n34' },
      { text: 'Was mache ich, wenn ich ein Testament gefunden habe?', ziel: 'n49' },
    ],
  },
  {
    id: 'n34',
    art: 'frage',
    text: 'Hat sich das Nachlassgericht bei Ihnen gemeldet?',
    antworten: [
      { text: 'Ja', ziel: 'n35' },
      { text: 'Nein', ziel: 'n39' },
    ],
  },
  {
    id: 'n35',
    art: 'frage',
    text: 'Wollen Sie das Erbe haben?',
    hinweis: 'Zum Erbe können auch Schulden des Verstorbenen gehören. Daher können auf den Erben Kosten zukommen. Außerdem kann es bei angespannten Situationen zwischen Erben zu Streitigkeiten kommen, die vor Gericht enden können. Wenn man das Erbe nicht will, dann erhält man nichts - also auch keinen Pflichtteil.',
    info: 'pflichtteil',
    antworten: [
      { text: 'Ja, ich will das Erbe', ziel: 'n37' },
      { text: 'Nein, ich will das Erbe nicht', ziel: 'n38' },
    ],
  },
  {
    id: 'n37',
    art: 'ergebnis',
    text: 'Sie sind Erbe.',
    status: 'erbe',
    antworten: [],
  },
  {
    id: 'n38',
    art: 'ergebnis',
    text: 'Sie wollen das Erbe nicht (Ausschlagung)\n**Folgende Schritte sind jetzt für Sie relevant:**\n\n**1. Frist**\nDie Frist beträgt 6 Wochen.\nFristbeginn:\n[gruen:Normalfall (gesetzliche Erbfolge):] Die Frist läuft ab dem Moment, in dem Sie erfahren, dass die Person gestorben ist und Sie gesetzlich erben.\n[gruen:Testament oder Erbvertrag:] Gibt es ein Testament, läuft die Frist erst los, wenn das Nachlassgericht Ihnen dieses Testament offiziell eröffnet und mitgeteilt hat – selbst wenn Sie vorher schon von dem Dokument wissen.\n\n**2. Wie können Sie das Erbe ablehnen?**\nSie haben dafür zwei Möglichkeiten:\n[gruen:1. Über ein Notariat:]\n• Termin bei einem Notar vereinbaren\n• Antrag auf Ausschlagung stellen\n• Notar beurkundet den Antrag und schickt ihn an das Nachlassgericht\n\n[gruen:2. Persönlich beim Gericht:]\n• telefonisch Termin beim Nachlassgericht vereinbaren\n• persönlich beim Nachlassgericht erscheinen\n\n**Notar oder Nachlassgericht:**\n• Beim Notar erhalten Sie schneller und sicher innerhalb der Frist einen Termin\n• Beim Nachlassgericht fallen Ihnen keine zusätzlichen Kosten an',
    aufgabe: 'ausschlagung',
    status: 'noch-erbe',
    gericht: true,
    kenntnisdatum: true,
    ausschlagungshinweis: true,
    antworten: [],
  },
  {
    id: 'n39',
    art: 'frage',
    text: 'Gibt es ein Testament?',
    antworten: [
      { text: 'Ja', ziel: 'n40' },
      { text: 'Nein', ziel: 'n45' },
    ],
  },
  {
    id: 'n40',
    art: 'frage',
    text: 'Sie müssen warten bis sich das Nachlassgericht meldet.',
    antworten: [
      { text: 'Das Nachlassgericht hat sich gemeldet', ziel: 'n41' },
    ],
  },
  {
    id: 'n41',
    art: 'frage',
    text: 'Wollen Sie das Erbe haben?',
    hinweis: 'Zum Erbe können auch Schulden des Verstorbenen gehören. Daher können auf den Erben Kosten zukommen. Außerdem kann es bei angespannten Situationen zwischen Erben zu Streitigkeiten kommen, die vor Gericht enden können. Wenn man das Erbe nicht will, dann erhält man nichts - also auch keinen Pflichtteil.',
    info: 'pflichtteil',
    antworten: [
      { text: 'Ja, ich will das Erbe', ziel: 'n43' },
      { text: 'Nein, ich will das Erbe nicht', ziel: 'n44' },
    ],
  },
  {
    id: 'n43',
    art: 'ergebnis',
    text: 'Sie sind Erbe.',
    status: 'erbe',
    antworten: [],
  },
  {
    id: 'n44',
    art: 'ergebnis',
    text: 'Sie wollen das Erbe nicht (Ausschlagung)\n**Folgende Schritte sind jetzt für Sie relevant:**\n\n**1. Frist**\nDie Frist beträgt 6 Wochen.\nFristbeginn:\n[gruen:Normalfall (gesetzliche Erbfolge):] Die Frist läuft ab dem Moment, in dem Sie erfahren, dass die Person gestorben ist und Sie gesetzlich erben.\n[gruen:Testament oder Erbvertrag:] Gibt es ein Testament, läuft die Frist erst los, wenn das Nachlassgericht Ihnen dieses Testament offiziell eröffnet und mitgeteilt hat – selbst wenn Sie vorher schon von dem Dokument wissen.\n\n**2. Wie können Sie das Erbe ablehnen?**\nSie haben dafür zwei Möglichkeiten:\n[gruen:1. Über ein Notariat:]\n• Termin bei einem Notar vereinbaren\n• Antrag auf Ausschlagung stellen\n• Notar beurkundet den Antrag und schickt ihn an das Nachlassgericht\n\n[gruen:2. Persönlich beim Gericht:]\n• telefonisch Termin beim Nachlassgericht vereinbaren\n• persönlich beim Nachlassgericht erscheinen\n\n**Notar oder Nachlassgericht:**\n• Beim Notar erhalten Sie schneller und sicher innerhalb der Frist einen Termin\n• Beim Nachlassgericht fallen Ihnen keine zusätzlichen Kosten an',
    aufgabe: 'ausschlagung',
    status: 'noch-erbe',
    gericht: true,
    kenntnisdatum: true,
    ausschlagungshinweis: true,
    antworten: [],
  },
  {
    id: 'n45',
    art: 'frage',
    text: 'Wollen Sie das Erbe haben?',
    hinweis: 'Zum Erbe können auch Schulden des Verstorbenen gehören. Daher können auf den Erben Kosten zukommen. Außerdem kann es bei angespannten Situationen zwischen Erben zu Streitigkeiten kommen, die vor Gericht enden können. Wenn man das Erbe nicht will, dann erhält man nichts - also auch keinen Pflichtteil.',
    info: 'pflichtteil',
    antworten: [
      { text: 'Ja, ich will das Erbe', ziel: 'n47' },
      { text: 'Nein, ich will das Erbe nicht', ziel: 'n48' },
    ],
  },
  {
    id: 'n47',
    art: 'ergebnis',
    text: 'Sie sind Erbe.',
    status: 'erbe',
    antworten: [],
  },
  {
    id: 'n48',
    art: 'ergebnis',
    text: 'Sie wollen das Erbe nicht (Ausschlagung)\n**Folgende Schritte sind jetzt für Sie relevant:**\n\n**1. Frist**\nDie Frist beträgt 6 Wochen.\nFristbeginn:\n[gruen:Normalfall (gesetzliche Erbfolge):] Die Frist läuft ab dem Moment, in dem Sie erfahren, dass die Person gestorben ist und Sie gesetzlich erben.\n[gruen:Testament oder Erbvertrag:] Gibt es ein Testament, läuft die Frist erst los, wenn das Nachlassgericht Ihnen dieses Testament offiziell eröffnet und mitgeteilt hat – selbst wenn Sie vorher schon von dem Dokument wissen.\n\n**2. Wie können Sie das Erbe ablehnen?**\nSie haben dafür zwei Möglichkeiten:\n[gruen:1. Über ein Notariat:]\n• Termin bei einem Notar vereinbaren\n• Antrag auf Ausschlagung stellen\n• Notar beurkundet den Antrag und schickt ihn an das Nachlassgericht\n\n[gruen:2. Persönlich beim Gericht:]\n• telefonisch Termin beim Nachlassgericht vereinbaren\n• persönlich beim Nachlassgericht erscheinen\n\n**Notar oder Nachlassgericht:**\n• Beim Notar erhalten Sie schneller und sicher innerhalb der Frist einen Termin\n• Beim Nachlassgericht fallen Ihnen keine zusätzlichen Kosten an',
    aufgabe: 'ausschlagung',
    status: 'noch-erbe',
    gericht: true,
    kenntnisdatum: true,
    ausschlagungshinweis: true,
    antworten: [],
  },
  {
    id: 'n49',
    art: 'ergebnis',
    text: 'Was mache ich, wenn ich ein Testament gefunden habe?\n• Testament unverzüglich beim zuständigen Nachlassgericht abgeben\n• Hinweis: Eine Nicht-Abgabe kann zu strafrechtlichen Folgen und Kosten für Sie führen.\n• Die Frist zur Abgabe ist unverzüglich (ohne schuldhaftes Zögern).',
    aufgabe: 'testament',
    gericht: true,
    antworten: [],
  },
  {
    id: 'n50',
    art: 'frage',
    text: 'Gibt es ein Testament?',
    antworten: [
      { text: 'Ja', ziel: 'n51' },
      { text: 'Ich weiß es nicht', ziel: 'n52' },
      { text: 'Nein', ziel: 'n53' },
      { text: 'Ich bin mir unsicher, ob das ein Testament ist', ziel: 'n54' },
      { text: 'Ich habe ein Testament gefunden', ziel: 'n56' },
    ],
  },
  {
    id: 'n51',
    art: 'ergebnis',
    text: 'Informationen zur Testamentsanfechtung\n\n**1.** **Was ist das?**\nEine Testamentsanfechtung bedeutet, dass ein Testament nachträglich für ungültig erklärt wird, weil beim Verfassen etwas grundlegend schiefgelaufen ist.\n\n**2.** **Wer darf anfechten?**\nPflichtteilsberechtigte: Kind, Ehegatte, Elternteil\n• Elternteile dürfen nur anfechten, wenn die Abkömmlinge der verstorbenen Person bereits verstorben sind.\n• Enkel dürfen nur anfechten, wenn das Elternteil, das Kind der verstorbenen Person ist, bereits verstorben ist.\nJeder, der bei gesetzlicher Erbfolge Erbe wäre.\nJeder, den ein vorheriges Testament zum Erben einsetzt.\n\n**3.** **Welche Gründe rechtfertigen eine Anfechtung?**\n• Verschreiben oder Versprechen: Die verstorbene Person wollte eigentlich etwas anderes schreiben, als am Ende im Testament steht.\n• Bedeutungsfehler: Die verstorbene Person nutzt einen Begriff, versteht dessen rechtliche oder tatsächliche Bedeutung aber falsch.\n• Falsche Beweggründe: Die verstorbene Person hat sich über die Zukunft oder über Tatsachen geirrt.\n• Drohung: Das Testament wurde nur verfasst, weil jemand die verstorbene Person unrechtmäßig unter Druck gesetzt oder bedroht hat.\n• Täuschung: Das Testament wurde nur verfasst, weil jemand die verstorbene Person getäuscht hat.\n**Nur für Pflichtteilsberechtigte:**\n• Die verstorbene Person hat beim Erstellen des Testaments nicht an Ehegatte, Elternteil oder Kind gedacht. Es kann aber davon ausgegangen werden, dass diese Person nach ihrem Willen Erbe werden sollte.\n• Die verstorbene Person wusste beim Verfassen nicht, dass es noch ein Kind gibt (zum Beispiel ein erst später geborenes Kind).\n\n**4.** **Folge der Anfechtung**\n• Das Testament wird ganz oder teilweise ungültig.\n• Es gilt dann entweder das ältere Testament oder das Erbrecht nach dem Gesetz.\n\n**5.** **Frist**\nFrist: 1 Jahr\nDie Frist beginnt, sobald Sie von dem Grund für die Anfechtung erfahren haben (siehe Schritt 3).\n\n**6.** **Kosten**\n• Durch die Anfechtung entstehen Kosten.\n  • Die Kosten werden gemildert oder entfallen bei wirksamer Anfechtung.',
    aufgabe: 'anfechtung',
    status: 'kein-erbe',
    gericht: true,
    anfechtungsdatum: true,
    antworten: [],
  },
  {
    id: 'n52',
    art: 'ergebnis',
    text: 'Wie erfahre ich, ob es ein Testament gibt?\nWeiß das Nachlassgericht von einem Testament, wird es Sie direkt benachrichtigen.\nErhalten Sie keine Post, können Sie sich beim Gericht selbst erkundigen, ob ein Testament vorliegt.\nGibt es kein Testament, meldet sich das Nachlassgericht ebenfalls bei Ihnen.',
    antworten: [],
  },
  {
    id: 'n53',
    art: 'ergebnis',
    text: 'Sie sind kein Erbe.',
    status: 'kein-erbe',
    antworten: [],
  },
  {
    id: 'n54',
    art: 'frage',
    text: 'Wie erkenne ich ein Testament?\n**Aussehen**\n• handschriftlich von der verstorbenen Person geschrieben\n• die Unterschrift der verstorbenen Person steht unter dem Text\n• das Wort „Testament“ ist nicht notwendig\n• ein Testament kann auf einem beliebigen Material geschrieben sein\n**Inhalt**\nDas Testament macht in irgendeiner Form deutlich, wie das Vermögen aufgeteilt wird.',
    antworten: [
      { text: 'Was mache ich, wenn ich ein Testament gefunden habe?', ziel: 'n55' },
    ],
  },
  {
    id: 'n55',
    art: 'ergebnis',
    text: 'Was mache ich, wenn ich ein Testament gefunden habe?\n• Testament unverzüglich beim zuständigen Nachlassgericht abgeben\n• Hinweis: Eine Nicht-Abgabe kann zu strafrechtlichen Folgen und Kosten für Sie führen.\n• Die Frist zur Abgabe ist unverzüglich (ohne schuldhaftes Zögern).',
    aufgabe: 'testament',
    gericht: true,
    antworten: [],
  },
  {
    id: 'n56',
    art: 'ergebnis',
    text: 'Was mache ich, wenn ich ein Testament gefunden habe?\n• Testament unverzüglich beim zuständigen Nachlassgericht abgeben\n• Hinweis: Eine Nicht-Abgabe kann zu strafrechtlichen Folgen und Kosten für Sie führen.\n• Die Frist zur Abgabe ist unverzüglich (ohne schuldhaftes Zögern).',
    aufgabe: 'testament',
    gericht: true,
    antworten: [],
  },
  {
    id: 'n57',
    art: 'frage',
    text: 'Gibt es ein Testament?',
    antworten: [
      { text: 'Ja', ziel: 'n58' },
      { text: 'Nein', ziel: 'n65' },
      { text: 'Ich weiß es nicht', ziel: 'n147' },
      { text: 'Ich habe ein Testament gefunden', ziel: 'n148' },
      { text: 'Ich bin mir unsicher, ob das ein Testament ist', ziel: 'n149' },
    ],
  },
  {
    id: 'n58',
    art: 'frage',
    text: 'Stehen Sie im Testament als Erbe?',
    antworten: [
      { text: 'Ja', ziel: 'n59' },
      { text: 'Nein', ziel: 'n64' },
    ],
  },
  {
    id: 'n59',
    art: 'frage',
    text: 'Sie sind Erbe außer es liegen Gründe zur Erbausschließung vor.',
    antworten: [
      { text: 'Was sind meine Möglichkeiten mit dem Erbe?', ziel: 'n60' },
    ],
  },
  {
    id: 'n60',
    art: 'frage',
    text: 'Wollen Sie das Erbe haben?',
    hinweis: 'Zum Erbe können auch Schulden des Verstorbenen gehören. Daher können auf den Erben Kosten zukommen. Außerdem kann es bei angespannten Situationen zwischen Erben zu Streitigkeiten kommen, die vor Gericht enden können. Wenn man das Erbe nicht will, dann erhält man nichts - also auch keinen Pflichtteil.',
    info: 'pflichtteil',
    antworten: [
      { text: 'Ja, ich will das Erbe', ziel: 'n62' },
      { text: 'Nein, ich will das Erbe nicht', ziel: 'n63' },
    ],
  },
  {
    id: 'n62',
    art: 'ergebnis',
    text: 'Sie sind Erbe.',
    status: 'erbe',
    antworten: [],
  },
  {
    id: 'n63',
    art: 'ergebnis',
    text: 'Sie wollen das Erbe nicht (Ausschlagung)\n**Folgende Schritte sind jetzt für Sie relevant:**\n\n**1. Frist**\nDie Frist beträgt 6 Wochen.\nFristbeginn:\n[gruen:Normalfall (gesetzliche Erbfolge):] Die Frist läuft ab dem Moment, in dem Sie erfahren, dass die Person gestorben ist und Sie gesetzlich erben.\n[gruen:Testament oder Erbvertrag:] Gibt es ein Testament, läuft die Frist erst los, wenn das Nachlassgericht Ihnen dieses Testament offiziell eröffnet und mitgeteilt hat – selbst wenn Sie vorher schon von dem Dokument wissen.\n\n**2. Wie können Sie das Erbe ablehnen?**\nSie haben dafür zwei Möglichkeiten:\n[gruen:1. Über ein Notariat:]\n• Termin bei einem Notar vereinbaren\n• Antrag auf Ausschlagung stellen\n• Notar beurkundet den Antrag und schickt ihn an das Nachlassgericht\n\n[gruen:2. Persönlich beim Gericht:]\n• telefonisch Termin beim Nachlassgericht vereinbaren\n• persönlich beim Nachlassgericht erscheinen\n\n**Notar oder Nachlassgericht:**\n• Beim Notar erhalten Sie schneller und sicher innerhalb der Frist einen Termin\n• Beim Nachlassgericht fallen Ihnen keine zusätzlichen Kosten an',
    aufgabe: 'ausschlagung',
    status: 'noch-erbe',
    gericht: true,
    kenntnisdatum: true,
    ausschlagungshinweis: true,
    antworten: [],
  },
  {
    id: 'n64',
    art: 'ergebnis',
    text: 'Informationen zur Testamentsanfechtung\n\n**1.** **Was ist das?**\nEine Testamentsanfechtung bedeutet, dass ein Testament nachträglich für ungültig erklärt wird, weil beim Verfassen etwas grundlegend schiefgelaufen ist.\n\n**2.** **Wer darf anfechten?**\nPflichtteilsberechtigte: Kind, Ehegatte, Elternteil\n• Elternteile dürfen nur anfechten, wenn die Abkömmlinge der verstorbenen Person bereits verstorben sind.\n• Enkel dürfen nur anfechten, wenn das Elternteil, das Kind der verstorbenen Person ist, bereits verstorben ist.\nJeder, der bei gesetzlicher Erbfolge Erbe wäre.\nJeder, den ein vorheriges Testament zum Erben einsetzt.\n\n**3.** **Welche Gründe rechtfertigen eine Anfechtung?**\n• Verschreiben oder Versprechen: Die verstorbene Person wollte eigentlich etwas anderes schreiben, als am Ende im Testament steht.\n• Bedeutungsfehler: Die verstorbene Person nutzt einen Begriff, versteht dessen rechtliche oder tatsächliche Bedeutung aber falsch.\n• Falsche Beweggründe: Die verstorbene Person hat sich über die Zukunft oder über Tatsachen geirrt.\n• Drohung: Das Testament wurde nur verfasst, weil jemand die verstorbene Person unrechtmäßig unter Druck gesetzt oder bedroht hat.\n• Täuschung: Das Testament wurde nur verfasst, weil jemand die verstorbene Person getäuscht hat.\n**Nur für Pflichtteilsberechtigte:**\n• Die verstorbene Person hat beim Erstellen des Testaments nicht an Ehegatte, Elternteil oder Kind gedacht. Es kann aber davon ausgegangen werden, dass diese Person nach ihrem Willen Erbe werden sollte.\n• Die verstorbene Person wusste beim Verfassen nicht, dass es noch ein Kind gibt (zum Beispiel ein erst später geborenes Kind).\n\n**4.** **Folge der Anfechtung**\n• Das Testament wird ganz oder teilweise ungültig.\n• Es gilt dann entweder das ältere Testament oder das Erbrecht nach dem Gesetz.\n\n**5.** **Frist**\nFrist: 1 Jahr\nDie Frist beginnt, sobald Sie von dem Grund für die Anfechtung erfahren haben (siehe Schritt 3).\n\n**6.** **Kosten**\n• Durch die Anfechtung entstehen Kosten.\n  • Die Kosten werden gemildert oder entfallen bei wirksamer Anfechtung.',
    aufgabe: 'anfechtung',
    status: 'kein-erbe',
    gericht: true,
    anfechtungsdatum: true,
    antworten: [],
  },
  {
    id: 'n65',
    art: 'frage',
    text: 'Ich bin {person}s …',
    disclaimer:
      'Die Ergebnisse der folgenden Fragen dienen ausschließlich der allgemeinen Information und Orientierung. Sie stellen keine Rechtsberatung dar und ersetzen nicht die individuelle Prüfung durch einen Anwalt oder Notar.',
    antworten: [
      { text: 'Ehegatte oder eingetragener Lebenspartner/in', ziel: 'n66' },
      { text: 'Kind', ziel: 'n67' },
      { text: 'Enkel/Enkelin', ziel: 'n68' },
      { text: 'Elternteil', ziel: 'n71' },
      { text: 'Geschwister', ziel: 'n74' },
      { text: 'Nichte/Neffe', ziel: 'n80' },
      { text: 'Großvater/Großmutter', ziel: 'n88' },
      { text: 'Onkel/Tante', ziel: 'n96' },
      { text: 'Cousin/Cousine', ziel: 'n108' },
      { text: 'Urgroßeltern', ziel: 'n122' },
      { text: 'Weiterer Verwandtschaftsgrad', ziel: 'n134' },
      { text: 'Keine Verwandtschaft', ziel: 'n146' },
    ],
  },
  {
    id: 'n66',
    art: 'ergebnis',
    text: 'Sie könnten nach der gesetzlichen Erbfolge Erbe sein.',
    status: 'wahrscheinlich-erbe',
    antworten: [],
  },
  {
    id: 'n67',
    art: 'ergebnis',
    text: 'Sie könnten nach der gesetzlichen Erbfolge Erbe sein.',
    status: 'wahrscheinlich-erbe',
    antworten: [],
  },
  {
    id: 'n68',
    art: 'frage',
    text: 'Lebt Ihr Elternteil noch? (Relevant ist nur das Elternteil, das ein Kind des Verstorbenen ist)',
    antworten: [
      { text: 'Ja', ziel: 'n69' },
      { text: 'Nein', ziel: 'n70' },
    ],
  },
  {
    id: 'n69',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n70',
    art: 'ergebnis',
    text: 'Sie könnten nach der gesetzlichen Erbfolge Erbe sein.',
    status: 'wahrscheinlich-erbe',
    antworten: [],
  },
  {
    id: 'n71',
    art: 'frage',
    text: 'Gibt es lebende Kinder, Enkel oder Urenkel des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n72' },
      { text: 'Nein', ziel: 'n73' },
    ],
  },
  {
    id: 'n72',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n73',
    art: 'ergebnis',
    text: 'Sie könnten nach der gesetzlichen Erbfolge Erbe sein.',
    status: 'wahrscheinlich-erbe',
    antworten: [],
  },
  {
    id: 'n74',
    art: 'frage',
    text: 'Gibt es lebende Kinder, Enkel oder Urenkel des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n75' },
      { text: 'Nein', ziel: 'n76' },
    ],
  },
  {
    id: 'n75',
    art: 'ergebnis',
    text: 'Sie sind kein Erbe.',
    status: 'kein-erbe',
    antworten: [],
  },
  {
    id: 'n76',
    art: 'frage',
    text: 'Leben Ihre Eltern noch?',
    antworten: [
      { text: 'Ja, beide', ziel: 'n77' },
      { text: 'Nur ein Elternteil', ziel: 'n78' },
      { text: 'Beide sind bereits verstorben', ziel: 'n79' },
    ],
  },
  {
    id: 'n77',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n78',
    art: 'ergebnis',
    text: 'Sie könnten nach der gesetzlichen Erbfolge Erbe sein.',
    status: 'wahrscheinlich-erbe',
    antworten: [],
  },
  {
    id: 'n79',
    art: 'ergebnis',
    text: 'Sie könnten nach der gesetzlichen Erbfolge Erbe sein.',
    status: 'wahrscheinlich-erbe',
    antworten: [],
  },
  {
    id: 'n80',
    art: 'frage',
    text: 'Gibt es lebende Kinder, Enkel oder Urenkel des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n81' },
      { text: 'Nein', ziel: 'n82' },
    ],
  },
  {
    id: 'n81',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n82',
    art: 'frage',
    text: 'Leben die Eltern des Verstorbenen noch?',
    antworten: [
      { text: 'Ja, beide leben noch', ziel: 'n83' },
      { text: 'Beide sind bereits verstorben', ziel: 'n84' },
      { text: 'Ein Elternteil lebt noch', ziel: 'n87' },
    ],
  },
  {
    id: 'n83',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n84',
    art: 'frage',
    text: 'Lebt Ihr Elternteil noch? (Relevant ist das Elternteil, das ein Geschwister des Verstorbenen ist)',
    antworten: [
      { text: 'Ja', ziel: 'n85' },
      { text: 'Nein', ziel: 'n86' },
    ],
  },
  {
    id: 'n85',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n86',
    art: 'ergebnis',
    text: 'Sie könnten nach der gesetzlichen Erbfolge Erbe sein.',
    status: 'wahrscheinlich-erbe',
    antworten: [],
  },
  {
    id: 'n87',
    art: 'frage',
    text: 'Lebt Ihr Elternteil noch? (Relevant ist nur das Elternteil, das ein Geschwister des Verstorbenen ist)',
    antworten: [
      { text: 'Ja', ziel: 'n151' },
      { text: 'Nein', ziel: 'n152' },
    ],
  },
  {
    id: 'n88',
    art: 'frage',
    text: 'Gibt es lebende Kinder, Enkel oder Urenkel des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n89' },
      { text: 'Nein', ziel: 'n90' },
    ],
  },
  {
    id: 'n89',
    art: 'ergebnis',
    text: 'Sie sind kein Erbe.',
    status: 'kein-erbe',
    antworten: [],
  },
  {
    id: 'n90',
    art: 'frage',
    text: 'Leben die Eltern des Verstorbenen noch?',
    antworten: [
      { text: 'Ja beide Elternteile leben noch', ziel: 'n91' },
      { text: 'Beide Elternteile sind bereits verstorben', ziel: 'n92' },
      { text: 'Ein Elternteil lebt noch', ziel: 'n95' },
    ],
  },
  {
    id: 'n91',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n92',
    art: 'frage',
    text: 'Gibt es lebende Geschwister, Nichten oder Neffen des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n93' },
      { text: 'Nein', ziel: 'n94' },
    ],
  },
  {
    id: 'n93',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n94',
    art: 'ergebnis',
    text: 'Sie könnten nach der gesetzlichen Erbfolge Erbe sein.',
    status: 'wahrscheinlich-erbe',
    antworten: [],
  },
  {
    id: 'n95',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n96',
    art: 'frage',
    text: 'Hat der Verstorbenen einen lebenden Ehegatten oder eingetragenen Lebenspartner/in?',
    antworten: [
      { text: 'Nein', ziel: 'n97' },
      { text: 'Ja', ziel: 'n107' },
    ],
  },
  {
    id: 'n97',
    art: 'frage',
    text: 'Gibt es lebende Kinder, Enkel oder Urenkel des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n98' },
      { text: 'Nein', ziel: 'n99' },
    ],
  },
  {
    id: 'n98',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n99',
    art: 'frage',
    text: 'Leben die Eltern des Verstorbenen noch?',
    antworten: [
      { text: 'Ja beide Elternteile leben noch', ziel: 'n100' },
      { text: 'Beide Elternteile sind bereits verstorben', ziel: 'n101' },
      { text: 'Ein Elternteil lebt noch', ziel: 'n106' },
    ],
  },
  {
    id: 'n100',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n101',
    art: 'frage',
    text: 'Gibt es lebende Geschwister, Nichten oder Neffen des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n102' },
      { text: 'Nein', ziel: 'n103' },
    ],
  },
  {
    id: 'n102',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n103',
    art: 'frage',
    text: 'Leben die Großeltern des Verstorbenen noch?',
    antworten: [
      { text: 'Ja', ziel: 'n104' },
      { text: 'Nein', ziel: 'n105' },
    ],
  },
  {
    id: 'n104',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n105',
    art: 'ergebnis',
    text: 'Sie könnten nach der gesetzlichen Erbfolge Erbe sein.',
    status: 'wahrscheinlich-erbe',
    antworten: [],
  },
  {
    id: 'n106',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n107',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n108',
    art: 'frage',
    text: 'Hat der Verstorbenen einen lebenden Ehegatten oder eingetragene Lebenspartner/in?',
    antworten: [
      { text: 'Nein', ziel: 'n109' },
      { text: 'Ja', ziel: 'n121' },
    ],
  },
  {
    id: 'n109',
    art: 'frage',
    text: 'Gibt es lebende Kinder, Enkel oder Urenkel des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n110' },
      { text: 'Nein', ziel: 'n111' },
    ],
  },
  {
    id: 'n110',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n111',
    art: 'frage',
    text: 'Leben die Eltern des Verstorbenen noch?',
    antworten: [
      { text: 'Ja beide Elternteile leben noch', ziel: 'n112' },
      { text: 'Beide Elternteile sind bereits verstorben', ziel: 'n113' },
      { text: 'Ein Elternteil lebt noch', ziel: 'n120' },
    ],
  },
  {
    id: 'n112',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n113',
    art: 'frage',
    text: 'Gibt es lebende Geschwister, Nichten oder Neffen des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n114' },
      { text: 'Nein', ziel: 'n115' },
    ],
  },
  {
    id: 'n114',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n115',
    art: 'frage',
    text: 'Leben die Großeltern des Verstorbenen noch?',
    antworten: [
      { text: 'Ja', ziel: 'n116' },
      { text: 'Nein', ziel: 'n117' },
    ],
  },
  {
    id: 'n116',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n117',
    art: 'frage',
    text: 'Lebt Ihr Elternteil noch? (Relevant ist das Elternteil, das blutsverwandt mit dem Verstorbenen ist)',
    antworten: [
      { text: 'Ja', ziel: 'n118' },
      { text: 'Nein', ziel: 'n119' },
    ],
  },
  {
    id: 'n118',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n119',
    art: 'ergebnis',
    text: 'Sie könnten nach der gesetzlichen Erbfolge Erbe sein.',
    status: 'wahrscheinlich-erbe',
    antworten: [],
  },
  {
    id: 'n120',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n121',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n122',
    art: 'frage',
    text: 'Hat der Verstorbenen einen lebenden Ehegatten oder eingetragene Lebenspartner/in?',
    antworten: [
      { text: 'Nein', ziel: 'n123' },
      { text: 'Ja', ziel: 'n133' },
    ],
  },
  {
    id: 'n123',
    art: 'frage',
    text: 'Gibt es lebende Kinder, Enkel oder Urenkel des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n124' },
      { text: 'Nein', ziel: 'n125' },
    ],
  },
  {
    id: 'n124',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n125',
    art: 'frage',
    text: 'Leben die Eltern des Verstorbenen noch?',
    antworten: [
      { text: 'Ja beide Elternteile leben noch', ziel: 'n126' },
      { text: 'Beide Elternteile sind bereits verstorben', ziel: 'n127' },
      { text: 'Ein Elternteil lebt noch', ziel: 'n132' },
    ],
  },
  {
    id: 'n126',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n127',
    art: 'frage',
    text: 'Gibt es lebende Geschwister, Nichten oder Neffen des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n128' },
      { text: 'Nein', ziel: 'n129' },
    ],
  },
  {
    id: 'n128',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n129',
    art: 'frage',
    text: 'Leben Großeltern, Tanten, Onkel, Cousin oder Cousinen des Verstorbenen noch?',
    antworten: [
      { text: 'Ja', ziel: 'n130' },
      { text: 'Nein', ziel: 'n131' },
    ],
  },
  {
    id: 'n130',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n131',
    art: 'ergebnis',
    text: 'Sie könnten nach der gesetzlichen Erbfolge Erbe sein.',
    status: 'wahrscheinlich-erbe',
    antworten: [],
  },
  {
    id: 'n132',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n133',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n134',
    art: 'frage',
    text: 'Hat der Verstorbenen einen lebenden Ehegatten oder eingetragene Lebenspartner/in?',
    antworten: [
      { text: 'Nein', ziel: 'n135' },
      { text: 'Ja', ziel: 'n145' },
    ],
  },
  {
    id: 'n135',
    art: 'frage',
    text: 'Gibt es lebende Kinder, Enkel oder Urenkel des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n136' },
      { text: 'Nein', ziel: 'n137' },
    ],
  },
  {
    id: 'n136',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n137',
    art: 'frage',
    text: 'Leben die Eltern des Verstorbenen noch?',
    antworten: [
      { text: 'Ja beide Elternteile leben noch', ziel: 'n138' },
      { text: 'Beide Elternteile sind bereits verstorben', ziel: 'n139' },
      { text: 'Ein Elternteil lebt noch', ziel: 'n144' },
    ],
  },
  {
    id: 'n138',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n139',
    art: 'frage',
    text: 'Gibt es lebende Geschwister, Nichten oder Neffen des Verstorbenen?',
    antworten: [
      { text: 'Ja', ziel: 'n140' },
      { text: 'Nein', ziel: 'n141' },
    ],
  },
  {
    id: 'n140',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n141',
    art: 'frage',
    text: 'Leben Großeltern, Tanten, Onkel, Cousin oder Cousinen des Verstorbenen noch?',
    antworten: [
      { text: 'Ja', ziel: 'n142' },
      { text: 'Nein', ziel: 'n143' },
    ],
  },
  {
    id: 'n142',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n143',
    art: 'ergebnis',
    text: 'Nach den Angaben lässt sich noch nicht sicher sagen, ob Sie Erbe sind.',
    antworten: [],
  },
  {
    id: 'n144',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n145',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n146',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n147',
    art: 'ergebnis',
    text: 'Wie erfahre ich, ob es ein Testament gibt?\nWeiß das Nachlassgericht von einem Testament, wird es Sie direkt benachrichtigen.\nErhalten Sie keine Post, können Sie sich beim Gericht selbst erkundigen, ob ein Testament vorliegt.\nGibt es kein Testament, meldet sich das Nachlassgericht ebenfalls bei Ihnen.',
    antworten: [],
  },
  {
    id: 'n148',
    art: 'ergebnis',
    text: 'Was mache ich, wenn ich ein Testament gefunden habe?\n• Testament unverzüglich beim zuständigen Nachlassgericht abgeben\n• Hinweis: Eine Nicht-Abgabe kann zu strafrechtlichen Folgen und Kosten für Sie führen.\n• Die Frist zur Abgabe ist unverzüglich (ohne schuldhaftes Zögern).',
    aufgabe: 'testament',
    gericht: true,
    antworten: [],
  },
  {
    id: 'n149',
    art: 'frage',
    text: 'Wie erkenne ich ein Testament?\n**Aussehen**\n• handschriftlich von der verstorbenen Person geschrieben\n• die Unterschrift der verstorbenen Person steht unter dem Text\n• das Wort „Testament“ ist nicht notwendig\n• ein Testament kann auf einem beliebigen Material geschrieben sein\n**Inhalt**\nDas Testament macht in irgendeiner Form deutlich, wie das Vermögen aufgeteilt wird.',
    antworten: [
      { text: 'Falls sie ein Testament gefunden haben', ziel: 'n150' },
    ],
  },
  {
    id: 'n150',
    art: 'ergebnis',
    text: 'Was mache ich, wenn ich ein Testament gefunden habe?\n• Testament unverzüglich beim zuständigen Nachlassgericht abgeben\n• Hinweis: Eine Nicht-Abgabe kann zu strafrechtlichen Folgen und Kosten für Sie führen.\n• Die Frist zur Abgabe ist unverzüglich (ohne schuldhaftes Zögern).',
    aufgabe: 'testament',
    gericht: true,
    antworten: [],
  },
  {
    id: 'n151',
    art: 'ergebnis',
    text: 'Sie sind wahrscheinlich kein Erbe.',
    status: 'wahrscheinlich-kein-erbe',
    antworten: [],
  },
  {
    id: 'n152',
    art: 'ergebnis',
    text: 'Sie könnten nach der gesetzlichen Erbfolge Erbe sein.',
    status: 'wahrscheinlich-erbe',
    antworten: [],
  },
]




